[tasks.install]
run = "bun install"
sources = ["package.json", "package-lock.json"]
outputs = ["node_modules/**"]

[tasks.dev]
run = "bun run dev -- --host 0.0.0.0 --port 3000"
depends = ["install"]

[tasks.build]
run = "bun run build"
depends = ["install"]
sources = [
  "package.json",
  "package-lock.json",
  "bun.lockb",
  "src/**",
  "public/**",
  "astro.config.mjs",
  "../libs/simulation-wasm/pkg/**"
]
outputs = ["dist/**"]

[tasks.start]
run = "bun run start -- --host 0.0.0.0 --port 3000"
depends = ["build"]
